# Generated by Django 5.0.14 on 2026-05-16 09:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_category_alter_article_body_article_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="bookmarks",
            field=models.ManyToManyField(
                blank=True,
                related_name="bookmarked_articles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
