# Generated by Django 5.0.14 on 2026-05-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_article_bookmarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
